spring:
  application:
    name: JabardastCoderBackend
  datasource:
    url: jdbc:postgresql://localhost:5432/jabardastcoder
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true